# Generated by Django 5.2.6 on 2025-11-05 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('creditnote', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRACompanyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tin', models.CharField(max_length=11)),
                ('bhf_id', models.CharField(default='00', max_length=2)),
                ('cmc_key', models.TextField(help_text='KRA CMC Key for authentication')),
                ('trade_name', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('top_message', models.CharField(blank=True, max_length=10)),
                ('bottom_message', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kra_config', to='companies.company')),
            ],
            options={
                'verbose_name': 'KRA Company Configuration',
                'verbose_name_plural': 'KRA Company Configurations',
            },
        ),
        migrations.CreateModel(
            name='KRAInvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_invoice_number', models.IntegerField(default=0)),
                ('last_credit_note_number', models.IntegerField(default=0)),
                ('last_used_date', models.DateField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kra_invoice_counter', to='companies.company')),
            ],
            options={
                'verbose_name': 'KRA Invoice Counter',
                'verbose_name_plural': 'KRA Invoice Counters',
            },
        ),
        migrations.CreateModel(
            name='KRAInvoiceSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kra_invoice_number', models.IntegerField()),
                ('trd_invoice_no', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], default='invoice', max_length=20)),
                ('submitted_data', models.JSONField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('success', 'Success'), ('signed', 'Signed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('receipt_signature', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kra_submissions', to='companies.company')),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kra_submissions', to='creditnote.creditnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kra_submissions', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'KRA Submission',
                'verbose_name_plural': 'KRA Submissions',
                'indexes': [models.Index(fields=['company', 'status'], name='kra_krainvo_company_28d67e_idx'), models.Index(fields=['invoice'], name='kra_krainvo_invoice_7817ce_idx'), models.Index(fields=['credit_note'], name='kra_krainvo_credit__b20d91_idx'), models.Index(fields=['kra_invoice_number'], name='kra_krainvo_kra_inv_7f850b_idx'), models.Index(fields=['document_type'], name='kra_krainvo_documen_eacc81_idx'), models.Index(fields=['trd_invoice_no'], name='kra_krainvo_trd_inv_3f1ad7_idx')],
                'unique_together': {('company', 'kra_invoice_number')},
            },
        ),
    ]
