# Generated by Django 5.2.6 on 2025-10-21 13:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_company_auto_invoice_number_and_more'),
        ('creditnote', '0002_creditnote_is_kra_validated_creditnote_subtotal_and_more'),
        ('kra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRACreditNoteSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kra_credit_note_number', models.CharField(blank=True, help_text='KRA-assigned credit note number', max_length=100, null=True)),
                ('receipt_signature', models.TextField(blank=True, help_text='KRA receipt signature', null=True)),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data from KRA', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to KRA'), ('success', 'Success'), ('signed', 'Signed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if submission failed', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the submission was sent to KRA', null=True)),
                ('validated_at', models.DateTimeField(blank=True, help_text='When KRA validation was completed', null=True)),
                ('kra_request', models.JSONField(blank=True, help_text='Raw request sent to KRA', null=True)),
                ('kra_response', models.JSONField(blank=True, help_text='Raw response from KRA', null=True)),
                ('attempt_count', models.IntegerField(default=1, help_text='Number of submission attempts')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, help_text='Last submission attempt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kra_credit_note_submissions', to='companies.company')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kra_submissions', to='creditnote.creditnote')),
            ],
            options={
                'db_table': 'kra_credit_note_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='kra_credit__company_d2f9e5_idx'), models.Index(fields=['credit_note', 'status'], name='kra_credit__credit__6cb002_idx'), models.Index(fields=['submitted_at'], name='kra_credit__submitt_d2c39f_idx'), models.Index(fields=['kra_credit_note_number'], name='kra_credit__kra_cre_1e805b_idx')],
            },
        ),
    ]
