# Generated by Django 5.2.6 on 2025-10-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_company_auto_invoice_number_and_more'),
        ('kra', '0002_kracreditnotesubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRACreditNoteCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_credit_note_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kra_credit_note_counter', to='companies.company')),
            ],
            options={
                'db_table': 'kra_credit_note_counter',
            },
        ),
    ]
