# Generated by Django 5.2.6 on 2025-10-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kra', '0003_kracreditnotecounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kracreditnotesubmission',
            name='kra_request',
        ),
        migrations.RemoveField(
            model_name='kracreditnotesubmission',
            name='kra_response',
        ),
        migrations.AddField(
            model_name='kracreditnotesubmission',
            name='response_data',
            field=models.JSONField(blank=True, help_text='Response from KRA', null=True),
        ),
        migrations.AddField(
            model_name='kracreditnotesubmission',
            name='submitted_data',
            field=models.JSONField(blank=True, help_text='Data submitted to KRA', null=True),
        ),
        migrations.AddField(
            model_name='kracreditnotesubmission',
            name='trd_credit_note_no',
            field=models.CharField(blank=True, help_text='Trading credit note number', max_length=100, null=True),
        ),
    ]
