# Generated by Django 5.2.6 on 2025-09-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activecompany'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_connected',
            new_name='is_connected_db',
        ),
    ]
