# Generated by Django 5.2.6 on 2025-09-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_company_qb_address_company_qb_company_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
