# Generated by Django 5.2.6 on 2025-09-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='brand_color',
            field=models.CharField(default='#0077C5', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_logo_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_template_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('Mentor', 'Client'), ('Mentee', 'Manager'), ('SystemAdmin', 'System Admin')], default='SystemAdmin', max_length=20),
        ),
    ]
