# Generated by Django 5.2.6 on 2025-10-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_invoice_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_template_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
