# Generated by Django 5.2.6 on 2025-10-15 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qb_invoice_id', models.CharField(db_index=True, max_length=50)),
                ('doc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('txn_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('customer_ref_value', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('private_note', models.TextField(blank=True, null=True)),
                ('customer_memo', models.TextField(blank=True, null=True)),
                ('sync_token', models.CharField(max_length=50)),
                ('template_id', models.CharField(blank=True, help_text='QuickBooks template ID used for this invoice', max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, help_text='Name of the QuickBooks template', max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_num', models.IntegerField()),
                ('item_ref_value', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_code_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['line_num'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'txn_date'], name='invoices_in_company_5a850d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['qb_invoice_id'], name='invoices_in_qb_invo_e2e1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer_name'], name='invoices_in_custome_e6ba5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('company', 'qb_invoice_id')},
        ),
        migrations.AlterUniqueTogether(
            name='invoiceline',
            unique_together={('invoice', 'line_num')},
        ),
    ]
