# Generated by Django 5.2.6 on 2025-10-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_kra_validated',
            field=models.BooleanField(default=False),
        ),
    ]
