# Generated by Django 5.2.6 on 2026-01-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('customers', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance_kes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Balance in KES', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_name',
            field=models.CharField(blank=True, help_text='Currency name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='currency_ref_value',
            field=models.CharField(blank=True, help_text='Currency code (e.g., USD, KES)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate to KES at transaction time', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal_kes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal in KES', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_total_kes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax total in KES', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amt_kes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount in KES', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='amount_kes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Line amount in KES', max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_amount_kes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax amount in KES', max_digits=15),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['currency_ref_value'], name='invoices_in_currenc_8410d7_idx'),
        ),
    ]
