# Generated by Django 5.2.6 on 2025-10-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_add_tax_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='template_id',
            field=models.CharField(blank=True, help_text='QuickBooks template ID used for this invoice', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='template_name',
            field=models.CharField(blank=True, help_text='Name of the QuickBooks template', max_length=255, null=True),
        ),
    ]
