# Generated by Django 5.2.6 on 2026-01-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_balance_kes_invoice_currency_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_kes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal_kes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_total_kes',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amt_kes',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='amount_kes',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='tax_amount_kes',
        ),
    ]
