# Generated by Django 5.2.6 on 2025-10-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_is_kra_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual tax percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate_ref',
            field=models.CharField(blank=True, help_text='QuickBooks TaxRateRef value', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual tax percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_rate_ref',
            field=models.CharField(blank=True, help_text='QuickBooks TaxRateRef value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='tax_code_ref',
            field=models.CharField(blank=True, help_text='QuickBooks TaxCodeRef value', max_length=50, null=True),
        ),
    ]
