# Generated by Django 5.2.6 on 2025-10-29 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_custom_logo'),
        ('customers', '0001_initial'),
        ('invoices', '0003_remove_invoiceline_tax_rate_invoice_tax_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='invoices_in_custome_bd64e2_idx'),
        ),
    ]
