# Generated by Django 5.2.6 on 2025-11-05 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qbo_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['state', 'used'], name='oauth_state_state_318c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthstate',
            index=models.Index(fields=['user', 'created_at'], name='oauth_state_user_id_3036dd_idx'),
        ),
    ]
