# Generated by Django 5.2.6 on 2025-10-15 12:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qb_customer_id', models.CharField(db_index=True, max_length=50)),
                ('display_name', models.CharField(db_index=True, max_length=255)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('bill_addr_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_addr_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_addr_city', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_addr_state', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_addr_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_addr_country', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_addr_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_addr_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_addr_city', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_addr_state', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_addr_postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_addr_country', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('balance_with_jobs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('sync_token', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('taxable', models.BooleanField(default=True)),
                ('tax_code_ref_value', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_code_ref_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['company', 'display_name'], name='customers_c_company_1f16d0_idx'), models.Index(fields=['company', 'email'], name='customers_c_company_898c5d_idx'), models.Index(fields=['company', 'active'], name='customers_c_company_615e80_idx'), models.Index(fields=['display_name'], name='customers_c_display_4c9536_idx')],
                'unique_together': {('company', 'qb_customer_id')},
            },
        ),
    ]
