# Generated by Django 5.2.6 on 2025-10-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_custom_logo'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_stub',
            field=models.BooleanField(default=False, help_text='Whether this is a stub customer created from invoice context'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'is_stub'], name='customers_c_company_aea717_idx'),
        ),
    ]
