# Generated by Django 5.2.6 on 2025-10-15 12:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Active Company',
                'verbose_name_plural': 'Active Companies',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('realm_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('qb_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_country', models.CharField(blank=True, max_length=100, null=True)),
                ('qb_address', models.JSONField(blank=True, null=True)),
                ('qb_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('qb_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qb_website', models.URLField(blank=True, null=True)),
                ('qb_fiscal_year_start', models.CharField(blank=True, max_length=20, null=True)),
                ('qb_supported_languages', models.CharField(blank=True, max_length=100, null=True)),
                ('qb_name_value', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_company_info', models.JSONField(blank=True, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('invoice_template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_logo_enabled', models.BooleanField(default=True)),
                ('brand_color', models.CharField(default='#0077C5', max_length=7)),
                ('invoice_footer_text', models.TextField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_data', models.JSONField(blank=True, null=True)),
                ('is_connected_db', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False)),
                ('role', models.CharField(default='member', max_length=50)),
            ],
        ),
    ]
