# Generated by Django 5.2.6 on 2025-11-05 11:21

import companies.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Active Company',
                'verbose_name_plural': 'Active Companies',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('realm_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_connected_db', models.BooleanField(default=False)),
                ('qb_company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_country', models.CharField(blank=True, max_length=100, null=True)),
                ('qb_address', models.JSONField(blank=True, null=True)),
                ('qb_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('qb_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qb_website', models.URLField(blank=True, null=True)),
                ('qb_fiscal_year_start', models.CharField(blank=True, max_length=20, null=True)),
                ('qb_supported_languages', models.CharField(blank=True, max_length=100, null=True)),
                ('qb_name_value', models.CharField(blank=True, max_length=255, null=True)),
                ('qb_company_info', models.JSONField(blank=True, null=True)),
                ('preferences_data', models.JSONField(blank=True, null=True)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('industry_type', models.CharField(blank=True, max_length=100, null=True)),
                ('company_start_date', models.DateField(blank=True, null=True)),
                ('ein', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_communication_addr', models.JSONField(blank=True, null=True)),
                ('legal_addr', models.JSONField(blank=True, null=True)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('multi_currency_enabled', models.BooleanField(default=False)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('tax_calculation', models.CharField(choices=[('TaxExcluded', 'Tax Excluded'), ('TaxIncluded', 'Tax Included')], default='TaxExcluded', max_length=20)),
                ('kra_pin', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='KRA PIN must be in the format A000000000B (one letter, nine digits, one letter).', regex='^[A-Z]\\d{9}[A-Z]$')])),
                ('custom_logo', models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_upload_to)),
                ('invoice_template_id', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_invoice_number', models.BooleanField(default=False)),
                ('default_payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('invoice_logo_enabled', models.BooleanField(default=True)),
                ('brand_color', models.CharField(default='#0077C5', max_length=7)),
                ('invoice_footer_text', models.TextField(blank=True, null=True)),
                ('time_tracking_enabled', models.BooleanField(default=False)),
                ('inventory_enabled', models.BooleanField(default=False)),
                ('class_tracking_enabled', models.BooleanField(default=False)),
                ('department_tracking_enabled', models.BooleanField(default=False)),
                ('customer_tracking_enabled', models.BooleanField(default=True)),
                ('vendor_tracking_enabled', models.BooleanField(default=True)),
                ('default_delivery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('default_ship_method', models.CharField(blank=True, max_length=100, null=True)),
                ('email_when_sent', models.BooleanField(default=False)),
                ('email_when_opened', models.BooleanField(default=False)),
                ('email_when_paid', models.BooleanField(default=False)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False)),
                ('role', models.CharField(default='member', max_length=50)),
            ],
        ),
    ]
