# Generated by Django 5.2.6 on 2025-10-15 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activecompany',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_users', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['realm_id'], name='companies_c_realm_i_44b149_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_c_name_2d8260_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user'], name='companies_c_user_id_ae9f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company'], name='companies_c_company_054520_idx'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['is_default'], name='companies_c_is_defa_5aa8e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companymembership',
            unique_together={('user', 'company')},
        ),
    ]
