# Generated by Django 5.2.6 on 2025-10-20 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='auto_invoice_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='class_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='company_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_communication_addr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='customer_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_delivery_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_ship_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='department_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='ein',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_when_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='email_when_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='email_when_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inventory_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_addr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='multi_currency_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='preferences_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_calculation',
            field=models.CharField(choices=[('TaxExcluded', 'Tax Excluded'), ('TaxIncluded', 'Tax Included')], default='TaxExcluded', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='time_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='vendor_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['currency_code'], name='companies_c_currenc_2b326c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_connected_db'], name='companies_c_is_conn_2c2531_idx'),
        ),
    ]
