# Generated by Django 5.2.6 on 2025-10-27 05:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_company_auto_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='KRA PIN must be in the format A000000000B (one letter, nine digits, one letter).', regex='^[A-Z]\\d{9}[A-Z]$')]),
        ),
    ]
