# Generated by Django 5.2.6 on 2025-10-27 07:47

import companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_kra_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_logo',
            field=models.ImageField(blank=True, null=True, upload_to=companies.models.company_logo_upload_to),
        ),
    ]
