# Generated by Django 5.2.6 on 2025-10-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_options_company_auto_invoice_number_and_more'),
        ('creditnote', '0001_initial'),
        ('invoices', '0002_invoice_is_kra_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='is_kra_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='tax_code_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='template_id',
            field=models.CharField(blank=True, help_text='QuickBooks template ID used for this credit note', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='template_name',
            field=models.CharField(blank=True, help_text='Name of the QuickBooks template', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['is_kra_validated'], name='creditnote__is_kra__7a50be_idx'),
        ),
    ]
