# Generated by Django 5.2.6 on 2026-01-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        ('creditnote', '0001_initial'),
        ('invoices', '0003_remove_invoice_balance_kes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='currency_name',
            field=models.CharField(blank=True, help_text='Currency name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='currency_ref_value',
            field=models.CharField(blank=True, help_text='Currency code (e.g., USD, KES)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, help_text='Exchange rate to KES at transaction time', max_digits=15),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['currency_ref_value'], name='creditnote__currenc_ba4ee3_idx'),
        ),
    ]
