# Generated by Django 5.2.6 on 2025-10-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_custom_logo'),
        ('creditnote', '0002_creditnote_is_kra_validated_creditnote_subtotal_and_more'),
        ('invoices', '0003_remove_invoiceline_tax_rate_invoice_tax_percent_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='creditnote',
            name='creditnote__is_kra__7a50be_idx',
        ),
        migrations.RemoveField(
            model_name='creditnoteline',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual tax percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tax_rate_ref',
            field=models.CharField(blank=True, help_text='QuickBooks TaxRateRef value', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual tax percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='tax_rate_ref',
            field=models.CharField(blank=True, help_text='QuickBooks TaxRateRef value', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='creditnoteline',
            name='tax_code_ref',
            field=models.CharField(blank=True, help_text='QuickBooks TaxCodeRef value', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['related_invoice'], name='creditnote__related_ee68d3_idx'),
        ),
    ]
