# Generated by Django 5.2.6 on 2026-01-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnote', '0002_creditnote_currency_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='test_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
