# Generated by Django 5.2.6 on 2026-01-28 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creditnote', '0003_creditnote_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='test_field',
        ),
    ]
