# Generated by Django 5.2.6 on 2026-01-28 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditnote', '0004_remove_creditnote_test_field'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='customers.customer'),
        ),
    ]
